apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: demo-httpd
    app.kubernetes.io/instance: demo-app-teste-production
  name: demo-httpd
  namespace: demo-app-teste
spec:
  port:
    targetPort: 80
